/* The site's menu tree. GlobalHeader renders it; GuideLayout walks it to work
   out a page's previous and next neighbours, so the order here is the reading
   order. Entries with isHeader are group labels, not links. */
export const NAV_LINKS = [
  { 
    name: "🐍 Python", 
    path: "/python",
    subLinks: [
      { name: "Python Overview", path: "/python" },
      { name: "1. Python Foundations", path: "/python/foundations" },
      { name: "2. Data Structures & Functions", path: "/python/data-structures" },
      { name: "3. OOP & Advanced Python", path: "/python/advanced" },
      { name: "4. System, Tooling & Async", path: "/python/tooling-async" },
      { name: "5. Data Science & ML", path: "/python/data-science" },
      { name: "6. Regular Expressions", path: "/python/regex" },
    ],
  },
  {
    name: "🤖 ML",
    path: "/ml",
    subLinks: [
      { name: "Introduction", path: "/ml" },
      { name: "Data & Statistics", isHeader: true },
      { name: "Data Sourcing", path: "/ml/data-sourcing" },
      { name: "Data Cleaning", path: "/ml/data-cleaning" },
      { name: "Data Analysis (EDA)", path: "/ml/data-analysis" },
      { name: "Bivariate Analysis", path: "/ml/bivariate-analysis" },
      { name: "Inferential Statistics", path: "/ml/inferential-statistics" },
      { name: "Central Limit Theorem", path: "/ml/central-limit-theorem" },
      { name: "Hypothesis Testing", path: "/ml/hypothesis-testing" },
      { name: "Foundations", isHeader: true },
      { name: "Supervised", path: "/ml/supervised" },
      { name: "Unsupervised", path: "/ml/unsupervised" },
      { name: "Classical", isHeader: true },
      { name: "Linear Reg", path: "/ml/linear-regression" },
      { name: "Multiple Linear Reg", path: "/ml/multiple-regression" },
      { name: "Logistic Reg", path: "/ml/logistic-regression" },
      { name: "Naive Bayes", path: "/ml/naive-bayes" },
      { name: "Decision Trees", path: "/ml/decision-trees" },
      { name: "KNN", path: "/ml/knn" },
      { name: "SVM", path: "/ml/svm" },
      { name: "Ensembles", isHeader: true },
      { name: "Random Forests", path: "/ml/random-forests" },
      { name: "XGBoost", path: "/ml/xgboost" },
      { name: "Deep Learning", isHeader: true },
      { name: "Neural Networks", path: "/ml/deep-learning" },
      { name: "CNNs", path: "/ml/cnn" },
      { name: "RNNs & LSTMs", path: "/ml/rnn" },
      { name: "GANs", path: "/ml/gans" },
      { name: "NLP", path: "/ml/nlp" },
      { name: "Transformers", path: "/ml/transformers" },
      { name: "Mamba / SSM", path: "/ml/mamba" },
      { name: "RWKV", path: "/ml/rwkv" },
      { name: "Reinforcement Learning", isHeader: true },
      { name: "RL Basics", path: "/ml/reinforcement-learning" },
      { name: "RLHF", path: "/ml/rlhf" },
      { name: "DPO & Variants", path: "/ml/dpo" },
      { name: "GRPO & RLVR", path: "/ml/grpo" },
      { name: "RLAIF & Constitutional AI", path: "/ml/rlaif" },
    ],
  },
  {
    name: "✨ GenAI",
    path: "/genai",
    subLinks: [
      { name: "AI Models", path: "/llms" },
      { name: "Model Types", isHeader: true },
      { name: "LLM · VLM · SLM · MoE · LCM · LAM", path: "/llms/types" },
      { name: "Decision Models (Jev, Laya)", path: "/genai/decision-models" },
      { name: "Core", isHeader: true },
      { name: "LLM Inference", path: "/llm-inference" },
      { name: "Efficient Inference", path: "/efficiency" },
      { name: "Prompt Engineering", path: "/prompting" },
      { name: "Tokenization", path: "/genai/tokenization" },
      { name: "Embeddings", path: "/rag/embeddings" },
      { name: "Adapting Models", isHeader: true },
      { name: "Fine-tuning", path: "/genai/fine-tuning" },
      { name: "PEFT Overview", path: "/genai/peft" },
      { name: "· LoRA", path: "/genai/peft/lora" },
      { name: "· QLoRA", path: "/genai/peft/qlora" },
      { name: "· DoRA", path: "/genai/peft/dora" },
      { name: "· Prefix / P-tuning", path: "/genai/peft/prefix-tuning" },
      { name: "· (IA)³", path: "/genai/peft/ia3" },
      { name: "· Adapter Layers", path: "/genai/peft/adapters" },
      { name: "Distillation", path: "/genai/distillation" },
      { name: "Quantization", path: "/genai/quantization" },
      { name: "Alignment: RLHF · DPO · GRPO", path: "/ml/rlhf" },
      { name: "More", isHeader: true },
      { name: "AGI & GPT-6 Astra", path: "/genai/agi" },
      { name: "Safety & Alignment", path: "/safety" },
    ],
  },
  {
    name: "🔍 RAG",
    path: "/rag",
    subLinks: [
      { name: "Fundamentals", path: "/rag/fundamentals" },
      { name: "Types of RAG", path: "/rag/types-of-rag" },
      { name: "Data Prep", path: "/rag/data-prep" },
      { name: "Indexing", path: "/rag/indexing" },
      { name: "Chunking", path: "/rag/chunking" },
      { name: "Embeddings", path: "/rag/embeddings" },
      { name: "Vector DBs", path: "/rag/vector-dbs" },
      { name: "Retrieval", path: "/rag/retrieval" },
      { name: "Adv Retrieval", path: "/rag/advanced-retrieval" },
      { name: "Compression", path: "/rag/compression" },
      { name: "Generation", path: "/rag/generation" },
      { name: "Evaluation", path: "/rag/evaluation" },
      { name: "Development", path: "/rag/development" },
      { name: "RAG vs Fine-tuning", path: "/rag/vs-fine-tuning" },
    ],
  },
  {
    name: "🕸️ Agents",
    path: "/agents",
    subLinks: [
      { name: "AI Agents", path: "/agents" },
      { name: "Tool Calling", path: "/agents/tool-calling" },
      { name: "Memory", path: "/agents/memory" },
      { name: "Document Loaders", path: "/agents/document-loaders" },
      { name: "Protocols", isHeader: true },
      { name: "MCP", path: "/mcp" },
      { name: "A2A Protocol", path: "/agents/a2a" },
      { name: "Orchestration", isHeader: true },
      { name: "Multi-Agent", path: "/agents/multi-agent" },
      { name: "Frameworks Compared", path: "/agents/frameworks" },
      { name: "LangChain + LangGraph", path: "/agents/langchain" },
      { name: "Debugging Agents", path: "/agents/debugging" },
    ],
  },
  {
    name: "🧩 Models",
    path: "/models",
    subLinks: [
      { name: "How Models Are Trained", path: "/models/training" },
      { name: "Families", isHeader: true },
      { name: "Claude", path: "/models/claude" },
      { name: "GPT", path: "/models/gpt" },
      { name: "Gemini", path: "/models/gemini" },
      { name: "Llama", path: "/models/llama" },
      { name: "Qwen", path: "/models/qwen" },
      { name: "DeepSeek", path: "/models/deepseek" },
      { name: "Mistral", path: "/models/mistral" },
      { name: "Grok", path: "/models/grok" },
      { name: "Gemma", path: "/models/gemma" },
      { name: "Cohere Command", path: "/models/command-r" },
      { name: "Phi-4", path: "/models/phi" },
      { name: "Claude Code Features", path: "/models/claude#claude-code" },
    ],
  },
  {
    name: "☁️ Cloud",
    path: "/azure",
    subLinks: [
      { name: "Azure", path: "/azure" },
      { name: "AWS", path: "/aws" }
    ],
  },
  {
    name: "🎓 Learn",
    path: "/roadmaps",
    subLinks: [
      { name: "Learning Paths", path: "/roadmaps" },
      { name: "Topic Map", path: "/graph" },
      { name: "Knowledge Checks", path: "/quizzes" },
      { name: "Interactive", path: "/interactive" },
      { name: "Glossary", path: "/glossary" },
    ],
  },
  {
    name: "🏗️ Build",
    path: "/system-design",
    subLinks: [
      { name: "System Design", path: "/system-design" },
      { name: "Projects", path: "/projects" },
      { name: "Resources", path: "/resources" },
    ],
  },
];

export const AZURE_LINKS = [
  { name: "Azure Basics", path: "/azure/basics" },
  { name: "Global Infrastructure", path: "/azure/infrastructure" },
  { name: "Azure Identity", path: "/azure/identity" },
  { name: "Virtual Machines", path: "/azure/vms" },
  { name: "Azure Storage", path: "/azure/storage" },
  { name: "Networking", path: "/azure/networking" },
  { name: "Load Balancer", path: "/azure/load-balancer" },
  { name: "Azure DNS", path: "/azure/dns" },
  { name: "App Service", path: "/azure/app-service" },
  { name: "AKS", path: "/azure/aks" },
  { name: "Azure Monitoring", path: "/azure/monitoring" },
  { name: "Azure Security", path: "/azure/security" },
  { name: "Backup & DR", path: "/azure/backup" },
  { name: "Architecture", path: "/azure/architecture" },
];

export const AWS_LINKS = [
  { name: "AWS Basics", path: "/aws/basics" },
  { name: "Global Infrastructure", path: "/aws/infrastructure" },
  { name: "IAM", path: "/aws/iam" },
  { name: "EC2", path: "/aws/ec2" },
  { name: "Storage Services", path: "/aws/storage" },
  { name: "Networking", path: "/aws/networking" },
  { name: "Load Balancer", path: "/aws/load-balancer" },
  { name: "Route 53 & DNS", path: "/aws/dns" },
];
